- name: Create local directory for admin.conf
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ local_k8s_directory }}"
    state: directory
    mode: "0755"

- name: Copy admin.conf from control panel node to local machine
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ local_k8s_directory }}/confg"
    flat: true
    become: true
