---
- name: Get join command
  ansible.buitin.command: kubeadm token create --print-join-command
  register: join_command_raw
  changed_when: true

- name: Set join command
  ansible.buitin.set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Create local directory for join command files
  ansible.buitin.delegate_to: localhost
  file:
    path: "{{ local_k8s_directory }}"
    state: directory

- name: Save join command to local file
  ansible.buitin.delegate_to: localhost
  ansible.builtin.shell:
    cmd: "echo '{{ join_command }}' > {{ local_k8s_directory }}/{{ ansible_host }}join_command.txt"
