---
- name: Kubeadm init
  ansible.builtin.command: sudo kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  changed_when: true

- name: Load iptable configuration
  ansible.builtin.shell: |
    mkdir -p /home/ubuntu/.kube
    sudo cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    sudo chown $(id -u):$(id -g) /home/ubuntu/.kube/config
  args:
    executable: /bin/bash
  changed_when: true
