---
- name: Kubeadm init
  ansible.builtin.command: sudo kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  changed_when: true
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#more-information

- name: Load iptable configuration
  ansible.builtin.command: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  changed_when: true
