- name: Create Docker registry secret
  kubernetes.core.k8s:
    state: present
    force: yes
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ namespace }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ {'auths': {'ghcr.io': {'username': github_username, 'password': github_token, 'email': email, 'auth': (github_username + ':' + github_token) | b64encode }}} | to_json | b64encode }}"