---
- name: Initialize iptable
  ansible.builtin.include_tasks: config_iptable.yml

- name: Install CRI-O Runtime
  ansible.builtin.include_tasks: install_crio_runtime.yml

- name: Install kubeadm Components
  ansible.builtin.include_tasks: install_k8s.yml

# - name: Reconfigure cni plugin
#   ansible.builtin.include_tasks: reconfigure_cni_plugins.yml
#   when: cni_plugin_reconfigure is defined and cni_plugin_reconfigure

# - name: Remove default cni plugins
#   ansible.builtin.include_tasks: delete_cni_plugins.yml
#   when: cni_plugin_delete is defined and cni_plugin_delete