---
- name: Install plugins
  ansible.builtin.shell: |
    # Install go
    cd ~
    sudo wget https://go.dev/dl/{{ go_archive }}
    sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.3.linux-amd64.tar.gz
    export PATH=$PATH:/usr/local/go/bin
    rm {{ go_archive }}

    # Install plugins
    git clone https://github.com/containernetworking/plugins
    cd plugins
    git checkout v1.1.1
    ./build_linux.sh
    sudo mkdir -p /opt/cni/bin
    sudo cp bin/* /opt/cni/bin/
    cd ..
    rm -rf plugins
  changed_when: true

- name: Create a config directory if it does not exist
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: directory
    mode: '0755'

- name: Copy CNI configuration to target directory
  ansible.builtin.copy:
    src: "{{ cni_plugin }}"
    dest: "/etc/cni/net.d/{{ cni_plugin }}"
    mode: "0755"
