---
- name: Install K3s on the worker nodes
  hosts: new_workers
  vars:
    TOKEN: K109fca5c03917ada568a12b8e9cd08cbc33da18fad61a92fb7b8f6b3dee7536bb2::server:bf2d7b0f0997bfe355335f072106e7ba
  become: yes
  tasks:
    - debug:
        msg: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['control_panel']['ansible_host'] }}:6443 K3S_TOKEN={{ TOKEN }} sh -"

    - name: join the nodes
      ansible.builtin.shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['control_panel']['ansible_host'] }}:6443 K3S_TOKEN={{ TOKEN }} sh -"
      args:
        executable: /bin/bash
