---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Configure a storage provisioner 
      kubernetes.core.k8s:
        state: present
        definition:
          kind: ConfigMap
          apiVersion: v1
          metadata:
            name: local-path-config
            namespace: local-path-storage
          data:
            config.json: |-
                  {
                          "nodePathMap":[
                          {
                                  "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                                  "paths":["/mnt/atached-volumn"]
                          },
                          {
                                  "node":"node-1",
                                  "paths":["/mnt/atached-volumn"]
                          },
                          {
                                  "node":"node-2",
                                  "paths":["/mnt/atached-volumn"]
                          }
                          ]
                  }
            setup: |-
                  #!/bin/sh
                  set -eu
                  mkdir -m 0777 -p "$VOL_DIR"
            teardown: |-
                  #!/bin/sh
                  set -eu
                  rm -rf "$VOL_DIR"
            helperPod.yaml: |-
                  apiVersion: v1
                  kind: Pod
                  metadata:
                    name: helper-pod
                  spec:
                    containers:
                    - name: helper-pod
                      image: busybox

    # - name: Create a Storage Class 
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: storage.k8s.io/v1
    #       kind: StorageClass
    #       metadata:
    #         name: local-storage
    #       provisioner: kubernetes.io/no-provisioner
    #       volumeBindingMode: WaitForFirstConsumer

    # - name: Create a PersistentVolume
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: v1
    #       kind: PersistentVolume
    #       metadata:
    #         name: cluster-pv 
    #       spec:
    #         capacity:
    #           storage: 50Gi
    #         volumeMode: Filesystem
    #         accessModes:
    #         - ReadWriteOnce
    #         persistentVolumeReclaimPolicy: Retain
    #         storageClassName: local-storage
    #         local:
    #           path: /mnt/attached-volumn
    #         nodeAffinity:
    #           required:
    #             nodeSelectorTerms:
    #             - matchExpressions:
    #               - key: kubernetes.io/hostname
    #                 operator: In
    #                 values:
    #                 - node-1 
    #                 - node-2 