- name: Initialize volume on worker nodes
  hosts: k8s_workers
  become: true
  tasks:
    - name: Create filesystem on volume
      ansible.builtin.command:
        cmd: mkfs.ext4 /dev/vdb
      changed_when: true

    - name: Create mount point directory
      ansible.builtin.file:
        path: /mnt/attached-volumn
        state: directory
        mode: "0755"

    - name: Mount the volume
      ansible.posix.mount:
        path: /mnt/attached-volumn
        src: /dev/vdb
        fstype: ext4
        state: mounted

    - name: Add volume to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "/dev/xvdb /mnt/attached-volumn ext4 defaults 0 0"
        state: present
