---
- name: Install K3s on the master node
  hosts: k3s_master
  become: yes
  tasks:
    - name: Download and install K3s on the master node
      ansible.builtin.shell: "curl -sfL https://get.k3s.io | sh -"
      args:
        executable: /bin/bash

    - name: Fetch the K3s node-token from the master node
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: tmp

    - name: set fact
      set_fact: k3s_nodetoken={{ tmp['content'] | b64decode | trim}}

    - debug:
        msg: "{{ k3s_nodetoken }}"

    - name: Fetch kubeconfig from the K3s server
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /Users/ericwhite/.kube/
        flat: yes

- name: Install K3s on the worker nodes
  hosts: k3s_workers
  become: yes
  tasks:
    - debug:
        msg: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['control_panel']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['control_panel']['k3s_nodetoken'] }} sh -"

    - name: join the nodes 
      ansible.builtin.shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['control_panel']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['control_panel']['k3s_nodetoken'] }} sh -"
      args:
        executable: /bin/bash
- name: Install addons
  hosts: k3s_master
  become: yes
  roles:
    - add-ons
