---
- name: Create filesystem on volume
  ansible.builtin.filesystem:
    dev: /dev/xvdb
    fstype: ext4

- name: Create mount point directory
  ansible.builtin.file:
    path: /mnt/
    state: directory

- name: Mount the volume
  ansible.builtin.mount:
    path: /mnt/my-pv
    src: /dev/xvdb
    fstype: ext4
    state: mounted

- name: Add volume to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/dev/xvdb /mnt/my-pv ext4 defaults 0 0"
    state: present
